### ISSUE TITLE
Move build machines to Qt 5.6.0

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#101]
This issue is to track moving to Qt 5.6.0, I see some failed builds on the dashboard from yesterday/today. Let's use this issue to track progress, and close when we have verified working binary installers for Windows and Mac OS X. See https://open.cdash.org/index.php?project=tomviz for current status

**Comment by mathturtle** [comment]
The latest OSX build succeeded during lunch.  I'll test the binaries in a minute.

**Comment by mathturtle** [comment]
They run... There's a weird issue with the menu bar though.
![Screenshot](https://cloud.githubusercontent.com/assets/553788/14049454/b8784268-f28b-11e5-8092-9c7997463253.png)
It seems to get slightly better when a dataset is loaded.
![screen shot 2016-03-25 at 1 17 47 pm](https://cloud.githubusercontent.com/assets/553788/14049493/075fc360-f28c-11e5-8001-416b2e8bed6b.png)
This only happened the first time I opened the application though.  Maybe just a random glitch?  I didn't notice anything else.

**Comment by cquammen** [comment]
I have seen some similar weird repainting (or lack thereof) issues with ParaView built against Qt 5.6. It happens when scrolling in the color map editor.

**Comment by cryos** [comment]
We can track that separately, if the basics work that is what I had hoped to track here. I will check it out later, and can take a look at Windows binaries later/over the weekend once they are ready.

**Comment by cryos** [comment]
Is Windows functional at this stage, I don't see any in-progress builds, and the builds yesterday all look like they failed. If it is backlogged then I can certainly look over the weekend once they complete.

**Comment by mathturtle** [comment]
Windows builds are working.  I tested running the binary and opening a file, but nothing fancy.

**Comment by cryos** [comment]
Thanks for testing this out Shawn, have a good weekend.

**Comment by cryos** [comment]
Closing this as we moved forward, but I think we should move to Qt 5.7.0 as it seems to have a number of fixes we could benefit from.
