### ISSUE TITLE
Linux binaries: CMake too old

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#105]
We recently updated ParaView to a newer version that requires CMake 3.5.  My linux docker buildslave uses 3.3.  Need to update the version of CMake in the container.  This is essentially a public note-to-self and lets people know that I've seen the failing builds and am working on it.

@cryos

**Comment by cryos** [comment]
Sure, I forgot they had bumped the CMake requirement.
