### ISSUE TITLE
Update paraview

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#109]
With @cryos's modificaitons to the data properties panel to remove the color map editor, we can update paraview again.  When I tested his branch on OSX, I tested with a newer ParaView and couldn't reproduce the scrolling issue since the QVTKWidget was no longer there.

Creating this to track updating ParaView.  This depends on updating the linux docker container to use CMake 3.5... I have an untested branch on buildbot which does this.

**Comment by cryos** [comment]
Are we ready to move ParaView forward yet? I would like to do this soon.

**Comment by mathturtle** [comment]
I just kicked off a test build of the new container... If it passes we should be good to merge the buildbot changes.

**Comment by mathturtle** [comment]
So something is broken with using newer CMake or the container.  CMake's GetPrerequisites is failing. I'm trying to track it down now.

**Comment by mathturtle** [comment]
Update: so the issue is a change in CMake so that silent failures are not so silent anymore.  Before, when get_prerequisites couldn't find some of the libraries it needed, it just assumed that they would be handled elsewhere and returned as complete a list as it could.  Now it fails and returns an empty list.  So I have to specify all libraries that tomviz links to in the get_prerequisites call.  And then handle where they get installed.  Working on it.

**Comment by mathturtle** [comment]
@cryos If we merge #111 then we can update ParaView.  It is the changes necessary to work with CMake 3.5.

**Comment by cryos** [comment]
Sounds good, that is merged now.
