### ISSUE TITLE
Move build machines to Qt 5.7.0

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#110]
This was released recently, and appears to have a number of important usability fixes. Let's move the build machines forward as soon as we have a chance.

**Comment by mathturtle** [comment]
I've installed 5.7 on bigmac and changed buildbot to use it.   And I deleted the build directory so the next build will be a clean build and use the new Qt.

**Comment by mathturtle** [comment]
Update, bigmac is working with Qt 5.7.  Praxis (the windows build machine) now has Qt 5.7 and should be doing a build against it now.

**Comment by mathturtle** [comment]
Update: Windows builds with Qt 5.7 are working.  Only Linux will still be on 5.6 for the 0.9 release since that build machine is harder to update.

**Comment by cryos** [comment]
Sounds good, were you able to verify the Windows executable produced functions as expected in basic testing? I know we have had a few people testing out the Mac binaries.

**Comment by mathturtle** [comment]
It can:
* load a dataset
* import everything in python
* run a basic python operator (so the python imports worked)

That is about all I tested, maybe a few more things, but I can't remember everything I tried offhand.

**Comment by mathturtle** [comment]
Linux binaries are switched to 5.7 too.  (I did that last week while I was fixing other dashboard machine stuff).
