### ISSUE TITLE
Consider CMake-ified Python

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#112]
@thewtex pointed out progress in the CMake-ified Python, and I think it is something we should revisit. Not sure we need to do it right now as we are stuck with Python 2.7 until ParaView moves forward, but once that is done it would be a good opportunity to move forward.

**Comment by cryos** [comment]
We should revisit this when we move to Python 3, which is now a viable option.

**Comment by cryos** [comment]
https://github.com/python-cmake-buildsystem/python-cmake-buildsystem is the build system I think I was pointed at, @thewtex please let me know if this is not the one you were referring to.

**Comment by thewtex** [comment]
@cryos Yes, that's it! +1 for adoption. It has Python 3 support.

CC @jcfr @chuckatkins

**Comment by jcfr** [comment]
Great news. Do not hesitate to create an issue if you have any questions.

Jc

**Comment by cryos** [comment]
We took a look, but for Windows were able to use the binaries provided by Python as they matched our Visual Studio version. It was a little rushed, but for Mac/Linux didn't get this working. We can revisit this in the future, sorry we didn't have more time to involve others, but we were in quite a time crunch too.

**Comment by jcfr** [comment]
Thanks for the update. :+1: 

> they matched our Visual Studio version

:+1:

> Mac/Linux didn't get this working

If you happen to have some log file or error message (even if incomplete) do not hesitate to report a bug on the tracker https://github.com/python-cmake-buildsystem/python-cmake-buildsystem
