### ISSUE TITLE
Windows packaging issues

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#128]
Problems found so far:
- We may want to fix this:
  Warning: In C:\bbd\a5bb74da\build\paraview\src\paraview\ParaViewCore\ServerManager\Core\vtkSMProxy.cxx, line 879
  vtkSMSourceProxy (000000000EFF2400): Proxy (filters, Probe)  has been deprecated in ParaView 5.2 and will be removed by ParaView 5.3. 
      This has been replaced by 'Resample With Dataset'. Please consider
      using that instead.
- This probably means I need to rebuild ITK.  @cquammen Can you send me a minimal CMakeCache of what ITK-specific options I need to turn on?  I can figure out the system specific stuff like the path to numpy...
  Exception encountered while running ConnectedComponents
  'itkTemplate' object has no attribute 'US3'

**Comment by cryos** [comment]
Sounds good, with ITK we need to be careful to sync up the building instructions with what is required. I also want to stick reasonably close to defaults/what we have, and make the smallest reasonable changes from there (unless we have a good reason to make larger changes, in which case we should discuss why they are necessary first).

**Comment by cquammen** [comment]
I can submit a patch for the warning later today. Should just be a class name substitution.

For ITK, the current build instructions will get you a working build of ITK 4.9. I have not been successful using other versions of ITK, so I would say stick with it for now. The default types for wrapping should be fine, but please ensure that ITK_WRAP_unsigned_short:BOOL=ON. At least some of the images we have are unsigned short type, and in my experience that type is common in microscopy data.

**Comment by mathturtle** [comment]
Note to future self:  ITK 4.9's Python wrapping cannot build with Visual Studio 2015.  You have to use 2013.

**Comment by cquammen** [comment]
Well rats. @cryos when do we want to spend time getting an ITK that works in VS 2015 and with the Python wrapping?

**Comment by cryos** [comment]
I am hoping that the ITK API is reasonably stable, if master builds with VS2015 can't we just use the same CMake configuration we would the 4.9, or have they broken other stuff for us in master? You might have to fill me in on the current challenges if that is not the case.

**Comment by mathturtle** [comment]
The few ITK things that didn't complain about unsigned short seemed to work even with the old binaries built with 2013.  We only access it through python anyway right now.  I think when we want to link to it directly and use the code in C++, then we have to care about this.

**Comment by cryos** [comment]
Sounds good, let's push this off for now then. If we cannot use the latest ITK it would be good to understand why, but we can track this in another issue dedicated to updating ITK which is a wider issue. If there are issues in ITK master we should put some time into tracking them, and seeing if we can get them addressed.

**Comment by cquammen** [comment]
Last I checked, ITK master as of a month or so ago, 4.9.1, and 4.10 had various problems:

* master - when running filters templated over unsigned char 3D image types, got the error `itk::ERROR: Failed dynamic cast to PN3itk5ImageItL3EEE object type = Image`
* 4.9.1 - failed with an igenerator.py error having to do with OptionParser being called with incorrect arguments
* 4.10 - had a PyBuffer error

I'll create in issue tracking ITK problems. 4.9 gives us what we need for now, but the latest release supposedly has much faster importing in Python, so that would be nice to get.

**Comment by mathturtle** [comment]
I tested yesterday and the ITK binaries need updating for unsigned short on all platforms.  My PR for this will include scripts that I have used to generate these binaries.  But OSX... why is ITK 4.9.0 downloading a castxml tar file that contains `castxml.exe`?

@thewtex This link https://midas3.kitware.com/midas/api/rest?method=midas.bitstream.download&checksum=9c317c45c93f94619f0879da6af058b0&name=castxml-macosx.tar.gz contains a windows build of castxml even though macosx is in the filename.

**Comment by thewtex** [comment]
@mathturtle Thanks for the note. The CastXML binaries were updated yesterday:

  http://review.source.kitware.com/#/c/21615/

A correction is here:

  http://review.source.kitware.com/#/c/21622

that swaps the MacOSX and Windows hashes.

**Comment by thewtex** [comment]
All issues @cquammen mentioned should be addressed ITK Git master.

**Comment by cryos** [comment]
Thanks for the update @thewtex, we should verify this is the case as we have time.

**Comment by mathturtle** [comment]
@thewtex Glad I could help find a bug :).

Also, oops I forgot the `git checkout ${target_tag}` line in my script... I wasn't actually wanting to build master.

**Comment by cryos** [comment]
I think we are done, and should open a new bug to track any new issues.
