### ISSUE TITLE
Update ITK

### ISSUE THREAD

**Issue by cquammen** [OpenChemistry/tomviz-superbuild#129]
Current version is 4.9.0. Version 4.10.1 promises faster import time in Python.

**Comment by thewtex** [comment]
ITK master has some NumPy conversion improvements used by tomviz, and I am currently fixing some wrapping issues for the Segment Pores operator.  Will make a note here when these are in master.

**Comment by cryos** [comment]
ITK is at 4.11 now, satisfying this wish. We will see if we have time to bump it again to bring in some of the latest changes.
