### ISSUE TITLE
Missing system runtime on windows 7

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#138]
Taken from @yijiang1's [comment on #745](https://github.com/OpenChemistry/tomviz/issues/745#issuecomment-259713452).  We are missing `api-ms-win-crt-runtime-l1-1-0.dll`.

After some investigation: it looks like more fallout from the switch to MSVC 2015.  In 2015, Microsoft split the runtime into two parts and CMake's InstallRequiredSystemLibraries didn't correctly detect which parts you needed until CMake 3.6.  So it sounds like we need to update the CMake on `praxis` and add a flag to use the new behavior.

**Comment by cryos** [comment]
Many of our systems already have Visual Studio installed, hence why it wasn't detected sooner. Thanks for following up on this @mathturtle, we need to get this fixed for the next release.

**Comment by mathturtle** [comment]
This should be fixed now.
