### ISSUE TITLE
SciPy integration

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#14]
We need to get SciPy integrated into the packaging process in order to expose it in the binaries we make available for download. SciPy has a hard dependency on Fortran, and so a Fortran compiler will also be necessary on the build machines.

**Comment by mathturtle** [comment]
Last night @utkarshayachit suggested that we look at WinPython: https://winpython.github.io/

**Comment by cryos** [comment]
Looks good, did the Fortran compiler not work out though? That sounded like a simple solution, if so I would rather stick with that and be finished. It seemed to be the recommendation on the SciPy list for quickest time to solution too.

**Comment by mathturtle** [comment]
I'm not finished testing it yet.  But I've only got this afternoon/evening before I leave and also I'm trying to get the crop widget working (I've been spending most of my time on that).

**Comment by cryos** [comment]
OK, see what you can get done, maybe send an email with updates before you need to leave. I would rather finish investigating the Fortran compiler option on Windows than look at this as it seems the fastest route, you already started looking into it, and we just want SciPy at this stage.

**Comment by Hovden** [comment]
Looks like SciPy is built into the tomviz! Tested a few scipy functions and rotation on current OSX and Windows cdash build.

**Comment by cryos** [comment]
That is great, glad to see this is working on both platforms now.
