### ISSUE TITLE
OSX Python 3

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#167]
Issue to report progress to migrating OSX builds to python 3.

You need the environment variable `CFLAGS=-I${CMAKE_OSX_SYSROOT}/usr/include` to make python build (obviously cmake will sub in the appropriate SDK location).  But the superbuild needs to add it to the build flags it gives the project otherwise they conflict and I haven't figured this out yet.

**Comment by mathturtle** [comment]
Look on bigmac in `~/shawn.waldon/tomviz/superbuild/src` for my WIP changes... it doesn't even build python yet though.

**Comment by cjh1** [comment]
@mathturtle I have pushed a wip branch #169

**Comment by cryos** [comment]
This is working great now, thanks for all the work you put into getting this to work!
