### ISSUE TITLE
Python and ITK 4.12 problems

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#194]
Linux: ITK wasn't packaged (needs investigation)

OSX: seems slow (possibly hangs?) if you are on OSX 10.12, otherwise trying to use python in tomviz fails due to a missing symbol.  This seems to be related to some change on bigmac since March, since 1.0 built fine and 1.0.1 fails.  Nothing with python has changed in the superbuild, so I suspect an OS or Xcode update is the cause.

Windows: Partially packaged but unusable (python module is missing from package, but C++ libraries are there).

**Comment by cryos** [comment]
Tracking this, from my recollection of discussions the Python build on macOS was broken by changes made in the common builder code that changed the SDK used. This was verified not to affect ParaView, but was missed for Tomviz. We should take measures to fully isolate build environments in my opinion as that would allow verification for the teams when they make changes, failing that we must ensure that changes to common code are better communicated even if they appear quite minor/trivial. I think @cjh1 had a workaround for the Python macOS issue.

I spoke with @thewtex last week at SciPy, there were no major changes made to ITK between 4.11 and 4.12 that would account for the packaging issues as far as he was aware. There were some changes to NumPy interaction from ITK that may need some attention.

We can use this issue as a tracker, any updates on Linux or Windows? I can spend some time this week looking into the build issues, I can definitely look into the macOS issues.

**Comment by mathturtle** [comment]
Update: I figured out what went wrong on Windows.  ITK 4.11 installed the python modules relative to the `CMAKE_INSTALL_PREFIX` in `bin/Lib/site-packages/itk`.  ITK 4.12 installs the python modules relative to python (either the exe or the libs, not sure), completely ignoring the `CMAKE_INSTALL_PREFIX`.  Since I was just zipping up the install tree and rearranging the components in the packaging steps my new binary didn't grab any of the python-related stuff.  @thewtex Is this intended and is there a way to make it install the python modules in the `CMAKE_INSTALL_PREFIX` like it used to?

**Comment by cryos** [comment]
I can see why you might do that to support ITK working out of the box perhaps, it seems to me that there should be a way to make ITK respect the install prefix specified. Mixing the ITK components with the Python install would make it more error prone for people like us making binary packages to extract the Python wrapped ITK modules. Any thoughts on exposing this as a build option @thewtex?

**Comment by thewtex** [comment]
ITK does have the wrapping in a potentially unique CMake install `COMPONENT`, so you can just get the Python wrapping by [setting `WRAP_ITK_INSTALL_COMPONENT_IDENTIFIER`](https://github.com/InsightSoftwareConsortium/ITK/blob/72e9386064c583701a35502f661c94d9f4d5884a/Wrapping/Generators/Python/CMakeLists.txt#L514). When `BUILD_SHARED_LIBS` is enabled, also get the [`RuntimeLibraries`](https://github.com/InsightSoftwareConsortium/ITK/blob/72e9386064c583701a35502f661c94d9f4d5884a/CMake/ITKModuleMacros.cmake#L398). This can be use to specify what gets installed [like this](https://github.com/InsightSoftwareConsortium/ITKPythonPackage/blob/0353eb66bae0b19ca1e12b0bafcbd339188a6648/CMakeLists.txt#L454-L463).

CC: @jcfr

**Comment by cryos** [comment]
Thanks @jcfr, that looks like it would restore the previous behavior with minimal changes to our build scripts.

**Comment by mathturtle** [comment]
I just tested out the Windows binary and ITK is working (although our conversion code is failing  OpenChemistry/tomviz#1211).  Linux just needs a minor fix to packaging to work (see #199).  OSX has worked for a couple days now.

**Comment by mathturtle** [comment]
Is this working.  I have tested Windows and Linux recently and they seem to work.  Did we get all the issues on OSX worked out?

**Comment by cquammen** [comment]
Yes, all is well. I have been using the nightly tomviz build to create examples of usage for the ITK-based filters.

**Comment by cryos** [comment]
Closing, these issues have been resolved.
