### ISSUE TITLE
SciPy version lags on macOS binaries

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#212]
At the tutorial at Berkeley Lab it was pointed out that the Windows version of SciPy is newer than that in the macOS package. We need to ensure all operating system packages bundle the same version (macOS lacks some features needed, and used from our Windows package to develop an atom tracing routine).

Looking at SciPy, they have released 1.0. We should move all three packages to that, and also push the NumPy version forward. Labeling this as a bug due to the version mismatch, but the upgrades are more an enhancement.

**Comment by cryos** [comment]
Just tracking what was said so we have a reference, let's do the minimal and ensure the macOS package matches the contents of the Windows package as far as version numbers go. Ideally make the Linux package follow that too, and we can bundle a 1.2.1. Once we have released we can track upgrading all platforms to the latest version.

**Comment by mathturtle** [comment]
All binaries now use Numpy 1.12.1 and Scipy 0.19.0 (or release candidates of those on Windows, they weren't out yet when I built our versions).

**Comment by cryos** [comment]
Closing as this is now  fixed.
