### ISSUE TITLE
Make sure packaged versions of dependencies are consistent across platforms

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#215]
After the inconsistent scipy/numpy versions were found we should check other dependencies to make sure they are using the same versions across platforms.

**Comment by cryos** [comment]
Is this complete at this stage? Please remember to circle back to issues and update them. I think it is, but if not let's outline what is remaining.

**Comment by mathturtle** [comment]
The only thing left is pyFFTW (0.10.4 (current release) on windows vs. 0.9.2 on mac/linux).

**Comment by cryos** [comment]
I think you told me that these are now consistent @mathturtle, if not what is remaining?

**Comment by mathturtle** [comment]
Yes, these are now consistent.
