### ISSUE TITLE
Bump to ParaView master for light kit panel

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#217]
Need to bump ParaView for the light kit panel, seems to work locally on Linux here. Once PV is bumped please take a quick look at the binaries produced to check for regressions. We can track anything that might pop up here. This is needed before the light kit PR for Tomviz can be merged.

**Comment by mathturtle** [comment]
Tested Mac and the new ParaView looks OK.

**Comment by mathturtle** [comment]
Linux seems OK too.

**Comment by mathturtle** [comment]
Windows also seems fine.  That said, neither of the two things that have broken recently were things I thought to test when we updated ParaView before... so I'm not sure how confident I am that everything is fine.

**Comment by cryos** [comment]
Some review is better than no review, making less frequent updates with some conscious testing is an improvement. I agree that we may not catch everything, but I think we can close this for now, and track testing in the future. Thanks.
