### ISSUE TITLE
VTK/ParaView removing Python packages from in-source third parties

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#226]
I think this will hit us when we update VTK/ParaView to latest master, but I'm not sure which Python packages we will care about.  `pygments` for sure since we use it for syntax highlighting of Python scripts.

Anyway, we'll have to update our superbuild to provide the missing Python modules.

@cquammen I know you've been working on getting ParaView updated, want to add any notes here for when we update tomviz's Paraview?

**Comment by cryos** [comment]
I think we package most of the big ones already, such as SciPy/NumPy. We definitely want to keep the syntax highlighting, thanks for being proactive on this. I hadn't realized we were particularly using anything from VTK/ParaView's third party Python stuff.

**Comment by cquammen** [comment]
We shouldn't need to do anything for the changes related to `mpi4py` as tomviz doesn't use MPI. I'm not sure if we need the web Python modules `autobahn`, `constantly`, `hyperlink`, `incremental`, `six`, `twisted`, `txaio`, `wslink`, `zopeinterface` for the web export capabilities - they may not be. @jourdain will know.

**Comment by jourdain** [comment]
You should be fine without those dependencies.

**Comment by cryos** [comment]
We have been disabling all of the web related stuff for quite some time, initially it was due to Python 3 issues, but as @jourdain said I don't think it will present any issues. He took care of separating out some of the dependencies when we added the web export feature.

**Comment by cryos** [comment]
Circling back, let's figure out what if anything was removed that we need. It sounds like pygments is still there. We should move ParaView forward soon, and make any adjustments needed. I have already fixed some things in our build system related to ParaView's config module no longer injecting Python variables into Tomviz - there may be other bits there too.

**Comment by mathturtle** [comment]
It looks like everything we need is still there (after I added a bunch of stuff to the python path anyway).  Apparently ParaView changed their install structure recently, so we'll have to update our python paths (and possibly bundling scripts) for that.

**Comment by mathturtle** [comment]
I think we are on a newer ParaView that this was referring to and this didn't really affect us.
