### ISSUE TITLE
Explore using kits in our packaged builds

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#227]
We discussed this at the last meeting, let's explore using kits and see what impact this has on the build/packaging. It should reduce load times, and if everything works have minimal impact.

**Comment by mathturtle** [comment]
My linux test build needed a VTK fix for kits, but after that worked just fine.

https://gitlab.kitware.com/vtk/vtk/merge_requests/3997

**Comment by mathturtle** [comment]
Hmmm. Looking at the python packages, from the other issue, it seems that ParaView has changed their python install locations, so updating ParaView will mean fixing the python path. (And we will need a very new ParaView for kits).

**Comment by cryos** [comment]
We can use this issue to track changes required to update ParaView. From what you just said the macOS packaging has shifted away from executable_path to use rpath. This will require updates to the macOS bundling logic as it does not recognize rpath.

**Comment by mathturtle** [comment]
The old ParaView install rules used to leave the library id equal to the library name (or full path I forget).  Our script used this to find the libraries and then used the install_name_tool to override their id with the executable_path version to set them relative to tomviz.  ParaView now installs its libraries with ids of `@rpath/libname.dylib`, which our script doesn't support.

**Comment by mathturtle** [comment]
Apparently updating ParaView means we need update the superbuild's minimum cmake version to 3.6.1 on all platforms.  New ParaView requires VTKm, and ExternalProject needs to do `git submodule update --init --recursive` (changed in 3.6).

**Comment by mathturtle** [comment]
It seems that new ParaView did not break the Windows packaging.

**Comment by mathturtle** [comment]
The ParaView update is in and issues related to that have settled now.  I've retested Mac and Linux packages with the fixes that have been merged and they are working again.  I'm making a branch for KITS now (testing locally on OSX produced a working bundle).

**Comment by mathturtle** [comment]
Something to be aware of:

Due to CMake bugs with object libraries only recently fixed, when the new module system lands in the fall using KITS will require CMake 3.12 (whereas ParaView/VTK will only bump to 3.9 or so).

**Comment by mathturtle** [comment]
OSX works, Linux I get some weird error:
```
#000: /home/buildslave/dev/itk/src/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5.c line 827 in H5open(): library initialization failed
    major: Function entry/exit
    minor: Unable to initialize object
  #001: /home/buildslave/dev/itk/src/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5.c line 212 in H5_init_library(): unable to initialize dataset interface
    major: Function entry/exit
    minor: Unable to initialize object
  #002: /home/buildslave/dev/itk/src/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Dint.c line 143 in H5D_init(): interface initialization failed
    major: Function entry/exit
    minor: Unable to initialize object
  #003: /home/buildslave/dev/itk/src/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5Dint.c line 185 in H5D__init_interface(): can't get default dataset creation property list
    major: Dataset
    minor: Inappropriate type
HDF5-DIAG: Error detected in HDF5 (1.8.17) thread 0:
  #000: /home/buildslave/dev/itk/src/Modules/ThirdParty/HDF5/src/itkhdf5/src/H5T.c line 1671 in H5Tcopy(): not a datatype or dataset
    major: Invalid arguments to routine
    minor: Inappropriate type
.... <snip>
```

I thought VTK's HDF5 should be mangled enough to avoid this sort of thing.

**Comment by mathturtle** [comment]
And Windows works.

**Comment by mathturtle** [comment]
ParaView's release branch missed a VTK fix for HDF5 mangling.  I just updated ParaView to a SHA on master that should have the HDF5 mangling fix.  I'll test the binaries later.

**Comment by cryos** [comment]
In looking at the Windows package I am a little confused - it doesn't seem to be using kits and has vtkRenderingCore, FreeType, Context2D etc.

**Comment by cryos** [comment]
PR #236 corrects the superbuild, let's verify the installer layout.
