### ISSUE TITLE
Qt 5.10 plus has issues with styles (widgets, color scheme)

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#237]
The Tomviz [bug](https://github.com/OpenChemistry/tomviz/issues/1502) documents the issues, reverting to Qt 5.9 and removing the setStyle call resolved it. When we move to 5.10+ we need to figure out style packaging, and verify on Windows that things look reasonable.

**Comment by cryos** [comment]
Updating to reflect that macOS clearly looks worse too on closer inspection (but not as bad as Windows). Side-by-side it is quite apparent.

**Comment by psavery** [comment]
I think this is fixed. Perhaps we can close?

**Comment by cryos** [comment]
Windows looks good, I am going to double check macOS before closing this.

**Comment by cryos** [comment]
This looks good with the latest builds, and now everything renders on first show too
