### ISSUE TITLE
MacOS 1.3.0-rc1 binary poor style

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#240]
We should move back to Qt 5.9 for the 1.3 release, there are clearly issues with style across platforms. It is a little more subtle on macOS, but still quite a regression.

**Comment by cquammen** [comment]
Qt 5.10 was really bad when we tried to switch ParaView 5.5 to use it.

**Comment by mathturtle** [comment]
OSX is reverted to 5.9.   Windows was reverted last week.
