### ISSUE TITLE
add hash to tomviz binary names

### ISSUE THREAD

**Issue by mathstuf** [OpenChemistry/tomviz-superbuild#25]
Copy mechanisms from paraview superbuild. A symlink should also be uploaded for `tomviz-latest.$ext` from the buildbot master (add extra factory steps).

**Comment by cryos** [comment]
The #26 has been closed, but this feature does not appear to be working, see https://open.cdash.org/viewFiles.php?buildid=4041407 for example - recent build with no hash in its file name.

**Comment by cryos** [comment]
Contrasting this with ParaView's for reference - https://open.cdash.org/viewFiles.php?buildid=4042121 is a recent example, with the functionality requested in this issue.

**Comment by mathturtle** [comment]
This is done.
