### ISSUE TITLE
Cannot find module 'six'

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#253]
Tomviz itself seems to work fine, but on startup it complains about not being able to find the 'six' python module.  Do I need to add this to the superbuild?

@cjh1 @cryos

**Comment by cjh1** [comment]
I thought six, was being pulled in as a dep of numpy etc. ?

**Comment by cjh1** [comment]
Looks like the python readers are pulling this in. I thought this was already packaged. @mathturtle Is going to add it.

**Comment by cryos** [comment]
Why are the Python readers pulling it in? We only need to support Python 3, is this something we can just avoid adding, or is it somehow more deeply useful than I realize?

**Comment by cjh1** [comment]
We can code it just to support Python 3.

**Comment by cryos** [comment]
I think that would be preferable, git grep shows it only in io. There is no intention to support Python 2.

**Comment by mathturtle** [comment]
The `six` dependency is removed by OpenChemistry/tomviz#1658
