### ISSUE TITLE
Building ParaView master on buildbot machines

### ISSUE THREAD

**Issue by cryos** [OpenChemistry/tomviz-superbuild#266]
Current status
- The Windows machine cannot build ParaView
- The macOS and Linux machine cannot link the Tomviz extension

**Comment by cryos** [comment]
Linux now has a weird `install DIRECTORY given non-directory` that started happening and it fails to even configure, but I suspect macOS and Linux can link (macOS definitely can), but packaging is broken due to different install locations.

**Comment by psavery** [comment]
On Linux, we might just need to change the line [here](https://github.com/OpenChemistry/tomviz-superbuild/blob/cc7554d9f9796e163a2e14d949eab1f2dc41e494/projects/unix/tomviz.bundle.cmake#L5) to say `paraview-5.5` instead of `paraview`. I'll confirm it further before submitting a PR.

**Comment by cryos** [comment]
Then we should submit a bug report or figure out how to get ParaView to remove the version as that is a regression. We enabled ParaView builds without versions for packaging etc where that versioning makes things more error prone. They may have changed the variable name, but I would like to avoid adding version numbers back in.

**Comment by cryos** [comment]
So Linux produced a package, but that segfaults on startup for me (I don't see the segfault with local builds):
```
ModuleNotFoundError: No module named 'tomviz'

Loguru caught a signal: SIGSEGV
Stack trace:
10      0x7f4df733acd3 clone + 67
9       0x7f4df8c19a92 /usr/lib/libpthread.so.0(+0x7a92) [0x7f4df8c19a92]
8       0x7f4df778b0ba /home/marcus/src/tomviz-superbuild/Tomviz-1.6.0-51-g170105d/bin/../lib/libQt5Core.so.5(+0xae0ba) [0x7f4df778b0ba]
7       0x7f4df778755d /home/marcus/src/tomviz-superbuild/Tomviz-1.6.0-51-g170105d/bin/../lib/libQt5Core.so.5(+0xaa55d) [0x7f4df778755d]
6             0x4cc03b QtConcurrent::RunFunctionTask<std::vector<tomviz::OperatorDescription> >::run() + 59
5             0x4ca340 tomviz::MainWindow::initPython() + 32
4             0x4c9e9b tomviz::MainWindow::findCustomOperators() + 619
3             0x54df26 tomviz::findCustomOperators(QString const&) + 278
2             0x54d2b1 tomviz::Python::Module::findFunction(QString const&) + 97
1       0x7f4e014dbb40 PyObject_GetAttrString + 0
0       0x7f4df8c244d0 /usr/lib/libpthread.so.0(+0x124d0) [0x7f4df8c244d0]
(   4.535s) [        E2253700]                       :0     FATL| Signal: SIGSEGV
```
The macOS build fails due to `RuntimeError: Unable to find the @rpath/libvtkClientServer-pv5.5.1.dylib` which appears to be a build issue in ParaView. Windows is having issues with ffmpeg and VTK/ParaView switching to imported targets for external dependencies breaking with our MINGW built ffmpeg, building it with MSVC is currently hitting zlib issues.

**Comment by cryos** [comment]
Linux looks like it is working now, probably needs more testing. Ben had a suggestion for macOS we can try, and Windows looks like it is getting close.

**Comment by cryos** [comment]
I think we actually have packages for all three platforms again now. We need to do more testing, verification, and I know the plugin stuff needs to come back, but definite progress has been made!

**Comment by psavery** [comment]
I think this is fixed. Perhaps we can close?
