### ISSUE TITLE
Windows package is pretty big

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz-superbuild#289]
The Windows zip file for previous releases was around 245MB. But it is currently 355MB. We should make sure we do not keep unnecessary parts inside that bloat it.

One thing we might be able to do to help remedy it is to remove modules of ITK that we do not plan on using. I think we are planning on removing some of the readers, for instance.

**Comment by cryos** [comment]
I think this is resolved now, it was mainly an issue with a missing `/` and then some extra install commands we didn't need.
