### ISSUE TITLE
Pygments not working on mac and linux

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz-superbuild#301]
For mac: even though pygments is being built and installed on the mac superbuild, it doesn't look like it gets included in the package for some reason.

Thus, there is still no python syntax highlighting on the mac binaries.

For linux (brought here from #302), pygments is installed correctly, but it is not found for some reason when running the tomviz binary. It is probably related to the use of easy-path.

**Comment by psavery** [comment]
It looks like it names itself something like `Pygments-2.4.2-py3.7.egg` in the `site-packages` directory. And then, it adds itself to the `easy-install.pth` install file so it can be found.

Because it isn't just named `pygments`, our installation doesn't find the module when packaging it on mac. Maybe we should install the `easy-install.pth` and all of the directories it refers to inside to fix the issue.

**Comment by psavery** [comment]
[Here](https://github.com/OpenChemistry/tomviz-superbuild/blob/8c9b16d1f8ce621893dd641b1e5387ed70c2fe71/projects/apple/tomviz.bundle.cmake#L63) is where the various modules are specified for installation on the Mac. I think on Windows and Linux, we just install the whole `site-packages` directory. We might be able to do it on mac as well to make things easier.

Here is the contents of `site-packages` on the mac superbuild:

```
Cython-0.29.7-py3.7-macosx-10.9-x86_64.egg
Pygments-2.4.2-py3.7.egg
README.txt
__pycache__
easy-install.pth
easy_install.py
numpy
numpy-1.16.3.dist-info
paraview
pip
pip-19.0.3.dist-info
pkg_resources
pyFFTW-0.10.4-py3.7.egg-info
pyfftw
scipy
scipy-1.2.1.dist-info
setuptools
setuptools-40.8.0.dist-info
vtk.py
vtkmodules

```

**Comment by psavery** [comment]
The other option might be to figure out a way to get it to name itself just `pygments`, so it can be found. That might fix #302 also. But I am not immediately sure how to do this...

**Comment by psavery** [comment]
Looks like `pip install .` installs it as `pygments`, making it more easily findable, if we use pip...

**Comment by cryos** [comment]
This sounds like a good path if it works reliably - let's pip install and use that.

**Comment by psavery** [comment]
The linux issue is now being tracked in this issue as well. Hopefully, it will be fixed by using `pip install .` also.

**Comment by psavery** [comment]
I think this is fixed now. We can re-open if not.
