### ISSUE TITLE
Pygments on Linux cannot be imported

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/tomviz-superbuild#302]
Although pygments on Linux is installed and packaged, it cannot be found or imported. This results in no python syntax highlighting for the Linux binaries (unless you have pygments installed locally, in which case it will be used).

My best guess as to the reason it can't be found has something to do with the fact that it is installed and packaged as a .egg directory in the `site-packages`, and that it is added to `easy-path.pth`. In theory, I think this should work, but it isn't for some reason...

**Comment by cryos** [comment]
We can probably just track in a single issue, but it looks like the change didn't help in the superbuild, I haven't had a chance to look at Windows yet.

**Comment by psavery** [comment]
Okay. Pygments on Windows was working when I tried it last. It was just Linux and Mac that weren't working (both for slightly different reasons, but both caused by a reliance on easy-path). I'll merge them into one issue.
