### ISSUE TITLE
Add ITK so that python operators can call it.

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#40]
We want to allow importing and using ITK filters for processing data in tomviz.

**Comment by mathturtle** [comment]
@cryos I finally got ITK with python built on OSX yesterday afternoon.  I can ```import itk``` and it succeeds.  I'm moving on to Windows today.

**Comment by mathturtle** [comment]
So do we want ITK or SimpleITK?  SimpleITK is separate (but requires you to have built ITK first, so I didn't waste any time).

**Comment by cryos** [comment]
ITK with its Python wrapping is great for now, we can assess whether SimpleITK is worth it later. We do want to bundle the Python wrapped ITK as provided by the ITK repository.

**Comment by mathturtle** [comment]
We can probably close this now.
