### ISSUE TITLE
Error when calling scipy functions

### ISSUE THREAD

**Issue by yijiang1** [OpenChemistry/tomviz-superbuild#93]
The current nightly binaries generates errors when calling scipy functions (on Mac).

To reproduce:
1. Load a sample data
2. Do a data transform that uses scipy function (say Downsample by 2)
Failed to execute the script. (:0, )
Traceback (most recent call last):
  File "Downsample x2", line 6, in transform_scalars
  File "/Applications/tomviz.app/Contents/Python/scipy/ndimage/__init__.py", line 172, in <module>
    from .filters import *
  File "/Applications/tomviz.app/Contents/Python/scipy/ndimage/filters.py", line 35, in <module>
    from . import _ni_support
ImportError: cannot import name _ni_support

**Comment by mathturtle** [comment]
Are you sure you have the latest binaries?  I can't reproduce this on my Mac.  Are you doing anything else differently?

**Comment by yijiang1** [comment]
I downloaded the binaries here:
<img width="948" alt="screen shot 2016-02-16 at 8 15 11 pm" src="https://cloud.githubusercontent.com/assets/13088588/13115944/edee2502-d567-11e5-926e-c200dcd73d0d.png">
This is the latest version right?

**Comment by cryos** [comment]
Yeah, although the links at http://www.tomviz.org/downloads should also get you the latest binary. I can take a look on my test system with these binaries.

**Comment by yijiang1** [comment]
I get the same error on the binary downloaded from http://www.tomviz.org/downloads

**Comment by cryos** [comment]
The version is in the application too, I am testing 0.7.2-38-g87d572c. This seems to be working as expected here too. You might try removing/deleting /Applications/tomviz.app, and reinstalling (not sure if Mac OS X does that for you when you select replace). I am testing on Yosemite, so I guess it could be an El Capitan issue?

**Comment by mathturtle** [comment]
No, I'm on El Capitan and it was fine for me.

**Comment by yijiang1** [comment]
> You might try removing/deleting /Applications/tomviz.app, and reinstalling

I tried this but get the same error:

Failed to execute the script. (:0, )
Traceback (most recent call last):
  File "Downsample x2", line 6, in transform_scalars
  File "/Applications/tomviz.app/Contents/Python/scipy/ndimage/__init__.py", line 172, in <module>
    from .filters import *
  File "/Applications/tomviz.app/Contents/Python/scipy/ndimage/filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "/Applications/tomviz.app/Contents/Python/scipy/misc/__init__.py", line 47, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/Applications/tomviz.app/Contents/Python/scipy/special/__init__.py", line 586, in <module>
    from ._ufuncs import *
ImportError: dlopen(/Applications/tomviz.app/Contents/Python/scipy/special/_ufuncs.so, 2): Library not loaded: /usr/local/Cellar/gcc/5.3.0/lib/gcc/5/libquadmath.0.dylib
  Referenced from: /Applications/tomviz.app/Contents/Libraries/libgfortran.3.dylib
  Reason: image not found

**Comment by cryos** [comment]
This looks new,

ImportError: dlopen(/Applications/tomviz.app/Contents/Python/scipy/special/_ufuncs.so, 2): Library not loaded: /usr/local/Cellar/gcc/5.3.0/lib/gcc/5/libquadmath.0.dylib
Referenced from: /Applications/tomviz.app/Contents/Libraries/libgfortran.3.dylib
Reason: image not found

Not seeing that here, and checking I don't have a /usr/local/Cellar, do you have something in your environment, such as PYTHONPATH or DYLD_LIBRARY_PATH, you can inspect this with the 'env' command.

**Comment by cquammen** [comment]
I'm thinking this is a problem on the build machine. gfortran looks like it was built with brew's gcc and picked up a dependency there. The installer will likely need to include this library.

**Comment by mathturtle** [comment]
Oh.  This again.  The problem is that _ufuncs.so (one of the scipy fortran python extensions) links to these:
```
/usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib
/usr/local/opt/gcc/lib/gcc/5/libquadmath.0.dylib
```
But `/usr/local/opt/gcc/lib/gcc/5/libgfortran.3.dylib` links to libquadmath at this path:
```
/usr/local/Cellar/gcc/5.3.0/lib/gcc/5/libquadmath.0.dylib
```

The packaging script doesn't realize that the two libquadmaths are the same library and then the one that doesn't exist on the system isn't found since only the other is fixed by the scripts.  @utkarshayachit helped me figure this out last time, but I don't remember what we ended up doing to fix it.  I think we just used `install_name_tool` to change path the libquadmath in libgfortran.3.dylib.  It must have been overwritten by a change in brew...

**Comment by cryos** [comment]
Yeah, brew gets updated from time to time. Strange that this works on my laptop, I do not have brew on there (and removed ports). I was trying to keep this machine pretty clean so that I could find issues like this.

**Comment by mathturtle** [comment]
@cryos Do you have scipy installed globally on your laptop?  That might be why it works...

**Comment by cryos** [comment]
I do apparently, in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras... I see the library with the bad path too, so I guess that explains why it was working locally.

**Comment by mathturtle** [comment]
@yijiang1 I merged a change that I think should fix this just now.  Can you try with the binaries that will generate tomorrow?

**Comment by Hovden** [comment]
I get an error (0.7.2-38-g87d572) on OSX:

Failed to execute the script. (:0, )
Traceback (most recent call last):
  File "Downsample x2", line 6, in transform_scalars
  File "/Applications/tomviz.app/Contents/Python/scipy/ndimage/__init__.py", line 172, in <module>
    from .filters import *
  File "/Applications/tomviz.app/Contents/Python/scipy/ndimage/filters.py", line 37, in <module>
    from scipy.misc import doccer
  File "/Applications/tomviz.app/Contents/Python/scipy/misc/__init__.py", line 47, in <module>
    from scipy.special import comb, factorial, factorial2, factorialk
  File "/Applications/tomviz.app/Contents/Python/scipy/special/__init__.py", line 586, in <module>
    from ._ufuncs import *
ImportError: dlopen(/Applications/tomviz.app/Contents/Python/scipy/special/_ufuncs.so, 2): Library not loaded: /usr/local/Cellar/gcc/5.3.0/lib/gcc/5/libquadmath.0.dylib
  Referenced from: /Applications/tomviz.app/Contents/Libraries/libgfortran.3.dylib
  Reason: image not found

**Comment by cryos** [comment]
We are tracking this now, I managed to miss this as I had a SciPy installed in my system path. I will remove that to make this kind of thing easier to spot in future. Hopefully #94 will address this issue.

**Comment by yijiang1** [comment]
I still get the same error on latest binaries.

**Comment by cryos** [comment]
Still trying to figure out why this won't fail locally as I deleted the scipy version that was getting loaded. I see that _ufuncs.so is linking to /usr/local/lib/gcc/5/libgcc_s.1.dylib, this does not exist locally. Also libquadmath.dylib is stating it lives in /usr/local/lib/gcc/5, and links to /usr/local/lib/gcc/5/libgcc_s.1.dylib in the latest app bundle.

**Comment by mathturtle** [comment]
I'm not sure about the libgcc_s.dylib links.  I may need to add another exception for system libraries to pull those in.

**Comment by cryos** [comment]
I doubt this is going to work without fixing that, and the location these libraries are reporting (full path that doesn't exist on my system). Tied up this afternoon, but I will look into simple ways to debug what we are really loading in our Python environment as this should not work on my Mac as far as I can tell.

**Comment by mathturtle** [comment]
I think this one is fixed now.

**Comment by yijiang1** [comment]
Right. There is no error on 0.8.0
