### ISSUE TITLE
Update to ITK 4.9.0

### ISSUE THREAD

**Issue by mathturtle** [OpenChemistry/tomviz-superbuild#97]
Ideally we want a minimal build of ITK for tomviz.  We will want to work out the minimal set of ITK to be compiled.  Eventually this will move from a precompiled library to something built in the tomviz superbuild.

We know we want these CMake options in addition to whichever options specify the platform:
```
BUILD_SHARED_LIBS:BOOL=ON
BUILD_TESTING:BOOL=OFF
ITK_WRAP_PYTHON:BOOL=ON
ITK_LEGACY_SILENT:BOOL=ON
ITK_LEGACY_REMOVE:BOOL=ON
ITK_USE_FFTWD:BOOL=ON
ITK_USE_FFTWF:BOOL=ON
ITK_USE_SYSTEM_FFTW:BOOL=ON
Module_BridgeNumPy:BOOL=ON
```

I don't know enough about the `ITK_WRAP_<datatype>` arguments to know which ones can be turned off.  When I tried turning off `rgb_unsigned_char` or `rgba_unsigned_char`, I got configure errors. Turning off `covariant_vector_float`, `complex_float` or `vector_float` gave warnings.

I'm creating this issue to figure out what this minimal ITK should look like since other people know a lot more about building ITK than I do.  The current CMake to generate our precompiled ITK lives in the Generating_ITK_binaries.md file in the root of this repository.

@cquammen @thewtex @cryos

**Comment by cquammen** [comment]
Regarding types, we'll want

`ITK_WRAP_signed_short`
`ITK_WRAP_float`

I think we *might* want

ITK_WRAP_signed_long

for certain labeling algorithms that might overflow the range representable by signed short, e.g., connected component labeling with many thousands of small regions from noise, for example.

**Comment by thewtex** [comment]
@mathturtle A build trim down will come from turning `ITK_BUILD_DEFAULT_MODULES`, then just turn on  `ITKGroup_Filtering`. Also, if it is only going to be used on 3D images, set `ITK_WRAP_IMAGE_DIMS` to `2`.

**Comment by cquammen** [comment]
I think @thewtex means set `ITK_WRAP_IMAGE_DIMS` to `3`.

**Comment by thewtex** [comment]
Yes, sorry for the typo :-)

**Comment by mathturtle** [comment]
I've rebuilt minimal ITK builds for OSX and Windows, but I'm having trouble on my docker image where we build the (experimental) Linux binaries.  I'm getting the following error.  Building on debian 7 with gcc 4.7.2:

```
/root/dev/itk/build/Wrapping/itkGradientRecursiveGaussianImageFilter.cxx:30:86: error: expected expression
    typedef itk::GradientRecursiveGaussianImageFilter< itk::Image< signed short,3 >, > itkGradientRecursiveGaussianImageFilterISS3;
                                                                                     ^
/root/dev/itk/build/Wrapping/itkGradientRecursiveGaussianImageFilter.cxx:31:86: error: expected expression
    typedef itk::GradientRecursiveGaussianImageFilter< itk::Image< signed short,3 >, >::Pointer itkGradientRecursiveGaussianIm...
                                                                                     ^
/root/dev/itk/build/Wrapping/itkGradientRecursiveGaussianImageFilter.cxx:31:89: error: definition or redeclaration of 'Pointer' cannot
      name the global scope
    typedef itk::GradientRecursiveGaussianImageFilter< itk::Image< signed short,3 >, >::Pointer itkGradientRecursiveGaussianIm...
                                                                                      ~~^
...
```

**Comment by thewtex** [comment]
@mathturtle The second template argument to itk::GradientRecursiveGaussianImageFilter is an itk::Image of itk::CovariantVector's -- make sure sufficient `ITK_WRAP_covariant_vector*` are turned on .  A covariant vector is the mathematical entity used to represent gradient values.

**Comment by mathturtle** [comment]
@thewtex I finally got back to this this afternoon.  Even after turning on all of the ITK_WRAP_<type> CMake variables, I still get this error.  I think for now, I'm just going to move the other builds to use ITK 4.9 and turn ITK off on the linux build.

**Comment by thewtex** [comment]
@mathturtle is there a Dockerfile or other way I can try to reproduce the linux build?

**Comment by mathturtle** [comment]
I was using the Dockerfile I sent you earlier for the tomviz builds (Debian 7 based).  I also got this same error on my machine without Docker (Ubuntu 15.10).  Here is the script I was using to configure ITK. (I had to change the extension before github would let me upload...  You may have to point it at your own external FFTW/Numpy (or take those out, I don't think they're related to the error).
[configure_itk.sh.txt](https://github.com/OpenChemistry/tomviz-superbuild/files/158945/configure_itk.sh.txt)

**Comment by thewtex** [comment]
@mathturtle Thanks for the script.  I was able to reproduce the error.  A patch is here:

  http://review.source.kitware.com/#/c/20852/

**Comment by mathturtle** [comment]
Python not finding ITK on OSX, investigate tomorrow.

**Comment by mathturtle** [comment]
This has been done for a while.
